apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8888
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:{{ .Values.env.CONFIG_SERVER_URL }}"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "{{ .Values.env.CONSUL_HOST }}"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "{{ .Values.env.CONSUL_PORT }}"
