apiVersion: v1
kind: Service
metadata:
  name: gateway-server
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: {{ .Values.service.type }}
