apiVersion: v1
kind: Service
metadata:
  name: gateway-server
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8888" # adapte au port de ton app
spec:
  selector:
    app: gateway-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: {{ .Values.service.type }}
