apiVersion: v1
kind: Service
metadata:
  name: admin-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8087" # adapte au port de ton app
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
  type: {{ .Values.service.type }}
