apiVersion: v1
kind: Service
metadata:
  name: paysan-service
spec:
  selector:
    app: paysan-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: {{ .Values.service.type }}
