apiVersion: v1
kind: Service
metadata:
  name: paysan-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8088" # adapte au port de ton app
spec:
  selector:
    app: paysan-service
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
  type: {{ .Values.service.type }}
