//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.05.19 at 11:12:52 PM WEST 
//


package io.spring.guides.gs_producing_web_service;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getInfoResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getInfoResponse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="numero_titre" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="localisation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="superficie_m2" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="usage" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="en_litige" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="hypothequee" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="date_enregistrement" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="proprietaires" type="{http://spring.io/guides/gs-producing-web-service}proprietaires"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getInfoResponse", propOrder = {
    "id",
    "numeroTitre",
    "localisation",
    "superficieM2",
    "usage",
    "enLitige",
    "hypothequee",
    "dateEnregistrement",
    "proprietaires"
})
public class GetInfoResponse {

    protected int id;
    @XmlElement(name = "numero_titre", required = true)
    protected String numeroTitre;
    @XmlElement(required = true)
    protected String localisation;
    @XmlElement(name = "superficie_m2", required = true)
    protected String superficieM2;
    @XmlElement(required = true)
    protected String usage;
    @XmlElement(name = "en_litige")
    protected boolean enLitige;
    protected boolean hypothequee;
    @XmlElement(name = "date_enregistrement", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dateEnregistrement;
    @XmlElement(required = true)
    protected Proprietaires proprietaires;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the numeroTitre property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroTitre() {
        return numeroTitre;
    }

    /**
     * Sets the value of the numeroTitre property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroTitre(String value) {
        this.numeroTitre = value;
    }

    /**
     * Gets the value of the localisation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalisation() {
        return localisation;
    }

    /**
     * Sets the value of the localisation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalisation(String value) {
        this.localisation = value;
    }

    /**
     * Gets the value of the superficieM2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuperficieM2() {
        return superficieM2;
    }

    /**
     * Sets the value of the superficieM2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuperficieM2(String value) {
        this.superficieM2 = value;
    }

    /**
     * Gets the value of the usage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsage() {
        return usage;
    }

    /**
     * Sets the value of the usage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsage(String value) {
        this.usage = value;
    }

    /**
     * Gets the value of the enLitige property.
     * 
     */
    public boolean isEnLitige() {
        return enLitige;
    }

    /**
     * Sets the value of the enLitige property.
     * 
     */
    public void setEnLitige(boolean value) {
        this.enLitige = value;
    }

    /**
     * Gets the value of the hypothequee property.
     * 
     */
    public boolean isHypothequee() {
        return hypothequee;
    }

    /**
     * Sets the value of the hypothequee property.
     * 
     */
    public void setHypothequee(boolean value) {
        this.hypothequee = value;
    }

    /**
     * Gets the value of the dateEnregistrement property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateEnregistrement() {
        return dateEnregistrement;
    }

    /**
     * Sets the value of the dateEnregistrement property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateEnregistrement(XMLGregorianCalendar value) {
        this.dateEnregistrement = value;
    }

    /**
     * Gets the value of the proprietaires property.
     * 
     * @return
     *     possible object is
     *     {@link Proprietaires }
     *     
     */
    public Proprietaires getProprietaires() {
        return proprietaires;
    }

    /**
     * Sets the value of the proprietaires property.
     * 
     * @param value
     *     allowed object is
     *     {@link Proprietaires }
     *     
     */
    public void setProprietaires(Proprietaires value) {
        this.proprietaires = value;
    }

}
