apiVersion: v1
kind: Service
metadata:
  name: terrain-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8083" # adapte au port de ton app
spec:
  selector:
    app: terrain-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: {{ .Values.service.type }}
