apiVersion: v1
kind: Service
metadata:
  name: terrain-service
spec:
  selector:
    app: terrain-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: {{ .Values.service.type }}
