replicaCount: 2

image:
  repository: ilyassoussi/gateway-server
  tag: 1.0.0.preprod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  CONFIG_SERVER_URL: http://server-config:8081
  CONSUL_HOST: server-consul
  CONSUL_PORT: 8500

ingress:
  enabled: true
  host: moussaada.34.46.8.60.nip.io  # ← adapte ce host si besoin

