apiVersion: v1
kind: Service
metadata:
  name: utilisateur-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8082" # adapte au port de ton app
spec:
  selector:
    app: utilisateur-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: {{ .Values.service.type }}
