apiVersion: v1
kind: Service
metadata:
  name: utilisateur-service
spec:
  selector:
    app: utilisateur-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: {{ .Values.service.type }}
