replicaCount: 1

image:
  repository: ilyassoussi/utilisateur-service
  tag: 1.0.0.preprod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8082

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  CONFIG_SERVER_URL: http://server-config:8081
  CONSUL_HOST: server-consul
  CONSUL_PORT: 8500
  DB_HOST: moussaadaa-postgres
  DB_PORT: 5432
  DB_NAME: utilisateur-db
  DB_USER: moussaadaDB
  DB_PASS: R3pp6sva