replicaCount: 1

image:
  repository: ilyassoussi/shared-micro
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8090

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 256Mi

env:
  CONFIG_SERVER_URL: http://server-config:8081
  CONSUL_HOST: server-consul
  CONSUL_PORT: 8500
