package org.gov.moussaada.subventions_service.model;

public enum Type_subv {
    IRRIGATION_GOUTTE_A_GOUTTE,
    IRRIGATION_PAR_ASPERSION,
    PLANTATION_OLIVIERS,
    PLANTATION_ARBRES_FRUITIERS,
    ELEVAGE_BOVINS,
    ELEVAGE_OVINS,
    MATERIEL_AGRICOLE,
    CONSTRUCTION_SERRE,
    TRANSFORMATION_PRODUITS,
    ENERGIE_SOLAIRES,
    CLÔTURE_TERRAIN,
    REBOISEMENT,
}
