apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-micro
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shared-micro
  template:
    metadata:
      labels:
        app: shared-micro
    spec:
      containers:
        - name: shared-micro
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:{{ .Values.env.CONFIG_SERVER_URL }}"
            - name: SPRING_CLOUD_CONSUL_HOST
              value: "{{ .Values.env.CONSUL_HOST }}"
            - name: SPRING_CLOUD_CONSUL_PORT
              value: "{{ .Values.env.CONSUL_PORT }}"
