apiVersion: v1
kind: Service
metadata:
  name: shared-micro
spec:
  selector:
    app: shared-micro
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: {{ .Values.service.type }}
