apiVersion: v1
kind: Service
metadata:
  name: shared-micro
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8090" # adapte au port de ton app
spec:
  selector:
    app: shared-micro
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: {{ .Values.service.type }}
