apiVersion: v1
kind: Service
metadata:
  name: subventions-service
spec:
  selector:
    app: paysan-service
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: {{ .Values.service.type }}
