replicaCount: 1

image:
  repository: ilyassoussi/server-config
  tag: 1.0.0.preprod
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8081

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 256Mi