apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-config
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: server-config
  template:
    metadata:
      labels:
        app: server-config
    spec:
      containers:
        - name: server-config
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
