apiVersion: v1
kind: Service
metadata:
  name: server-config
spec:
  selector:
    app: server-config
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: {{ .Values.service.type }}
