apiVersion: v1
kind: Service
metadata:
  name: server-config
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081" # adapte au port de ton app
spec:
  selector:
    app: server-config
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: {{ .Values.service.type }}
