name: CI/CD Server Config to GKE

on:
  push:
    branches: [master]
    paths:
      - 'admin-service/**'

env:
  IMAGE_NAME: admin-service

jobs:
  setup:
    name: Setup & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: admin-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Maven settings.xml for GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>ilyassoussi</username>
                <password>${{ secrets.TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF
      - name: Build JAR
        run: ./mvnw clean package -DskipTests

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: admin-service-jar
          path: admin-service/target/*.jar

  sonarqube-check:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: admin-service-jar
          path: admin-service/target/

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./admin-service
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_ADMIN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: sonarqube-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR
        uses: actions/download-artifact@v4
        with:
          name: admin-service-jar
          path: admin-service/target/

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Create Maven settings.xml
        run: |
          mkdir -p admin-service/.m2
          cat > admin-service/.m2/settings.xml <<EOF
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>ilyassoussi</username>
                <password>${{ secrets.TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build & Push Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ github.sha }} admin-service
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:${{ github.sha }}

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GKE_CREDENTIALS }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          install_components: 'gke-gcloud-auth-plugin'

      - name: Get GKE Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --zone ${{ secrets.GKE_ZONE }} \
            --project ${{ secrets.GKE_PROJECT }}

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Deploy to GKE with Helm
        run: |
          helm upgrade --install $IMAGE_NAME ./admin-service/helm/ \
            --set image.repository=${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME \
            --set image.tag=${{ github.sha }}
